/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationPanel: typeof import('./src/components/property-panel/AnimationPanel.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AssetLibrary: typeof import('./src/components/sider/AssetLibrary.vue')['default']
    AudioPreviewCard: typeof import('./src/components/AudioPreviewCard.vue')['default']
    AudioPropertyPanel: typeof import('./src/components/property-panel/AudioPropertyPanel.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    ChatMessageItem: typeof import('./src/components/chat/ChatMessageItem.vue')['default']
    ChatPanel: typeof import('./src/components/chat/ChatPanel.vue')['default']
    CommonProperties: typeof import('./src/components/property-panel/CommonProperties.vue')['default']
    DebugPanel: typeof import('./src/components/DebugPanel.vue')['default']
    ExportProgressModal: typeof import('./src/components/ExportProgressModal.vue')['default']
    FilterPanel: typeof import('./src/components/FilterPanel.vue')['default']
    ImagePreviewCard: typeof import('./src/components/ImagePreviewCard.vue')['default']
    ImagePropertyPanel: typeof import('./src/components/property-panel/ImagePropertyPanel.vue')['default']
    MediaClipPanel: typeof import('./src/components/property-panel/MediaClipPanel.vue')['default']
    MediaCropBoxOverlay: typeof import('./src/components/MediaCropBoxOverlay.vue')['default']
    Modal: typeof import('./src/components/ui/modal/Modal.vue')['default']
    Nav: typeof import('./src/components/sider/Nav.vue')['default']
    NavItem: typeof import('./src/components/sider/NavItem.vue')['default']
    PlaybackControls: typeof import('./src/components/PlaybackControls.vue')['default']
    PropertyPanel: typeof import('./src/components/property-panel/PropertyPanel.vue')['default']
    ResizableTimeline: typeof import('./src/components/ResizableTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectionGroup: typeof import('./src/components/SelectionGroup.vue')['default']
    Sider: typeof import('./src/components/sider/Sider.vue')['default']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    TextPropertyPanel: typeof import('./src/components/property-panel/TextPropertyPanel.vue')['default']
    TimelineTransitionHandles: typeof import('./src/components/TimelineTransitionHandles.vue')['default']
    TimelineWrapper: typeof import('./src/components/TimelineWrapper.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    TransitionPanel: typeof import('./src/components/TransitionPanel.vue')['default']
    VideoPreviewCard: typeof import('./src/components/VideoPreviewCard.vue')['default']
    VideoPreviewList: typeof import('./src/components/VideoPreviewList.vue')['default']
    VideoPropertyPanel: typeof import('./src/components/property-panel/VideoPropertyPanel.vue')['default']
  }
}
